# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 720)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ModeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ModeLabel.setGeometry(QtCore.QRect(10, 225, 401, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.ModeLabel.setFont(font)
        self.ModeLabel.setObjectName("ModeLabel")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(10, 620, 50, 51))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(21)
        font.setKerning(False)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.SettingsButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SettingsButton.setStyleSheet("")
        self.SettingsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsButton.setIcon(icon)
        self.SettingsButton.setAutoDefault(False)
        self.SettingsButton.setDefault(False)
        self.SettingsButton.setFlat(False)
        self.SettingsButton.setObjectName("SettingsButton")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(274, 622, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.RunButton.setFont(font)
        self.RunButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.RunButton.setObjectName("RunButton")
        self.RGD = QtWidgets.QLabel(self.centralwidget)
        self.RGD.setGeometry(QtCore.QRect(10, 10, 401, 200))
        self.RGD.setText("")
        self.RGD.setObjectName("RGD")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 250, 401, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "Расстояние")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню"))
        self.ModeLabel.setText(_translate("MainWindow", "Выбор режима:"))
        self.RunButton.setText(_translate("MainWindow", "Запустить"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Проверка на встречу"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Расписание"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Изменение расписания"))
