# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimetableWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimetableWindow(object):
    def setupUi(self, TimetableWindow):
        TimetableWindow.setObjectName("TimetableWindow")
        TimetableWindow.resize(420, 720)
        self.InputLine = QtWidgets.QLineEdit(TimetableWindow)
        self.InputLine.setGeometry(QtCore.QRect(20, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputLine.setFont(font)
        self.InputLine.setObjectName("InputLine")
        self.label_5 = QtWidgets.QLabel(TimetableWindow)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ResultBrowser = QtWidgets.QTextBrowser(TimetableWindow)
        self.ResultBrowser.setGeometry(QtCore.QRect(20, 150, 381, 501))
        self.ResultBrowser.setObjectName("ResultBrowser")
        self.ComleteBut = QtWidgets.QPushButton(TimetableWindow)
        self.ComleteBut.setGeometry(QtCore.QRect(250, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComleteBut.setFont(font)
        self.ComleteBut.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ComleteBut.setObjectName("ComleteBut")
        self.BackButton = QtWidgets.QPushButton(TimetableWindow)
        self.BackButton.setGeometry(QtCore.QRect(260, 660, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BackButton.setObjectName("BackButton")
        self.InputLine_2 = QtWidgets.QLineEdit(TimetableWindow)
        self.InputLine_2.setGeometry(QtCore.QRect(230, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputLine_2.setFont(font)
        self.InputLine_2.setObjectName("InputLine_2")
        self.label_6 = QtWidgets.QLabel(TimetableWindow)
        self.label_6.setGeometry(QtCore.QRect(230, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(TimetableWindow)
        self.label.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.reverseBut = QtWidgets.QPushButton(TimetableWindow)
        self.reverseBut.setGeometry(QtCore.QRect(192, 52, 37, 37))
        self.reverseBut.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.reverseBut.setObjectName("reverseBut")

        self.retranslateUi(TimetableWindow)
        QtCore.QMetaObject.connectSlotsByName(TimetableWindow)

    def retranslateUi(self, TimetableWindow):
        _translate = QtCore.QCoreApplication.translate
        TimetableWindow.setWindowTitle(_translate("TimetableWindow", "Расписание"))
        self.label_5.setText(_translate("TimetableWindow", "Станция отправления:"))
        self.ComleteBut.setText(_translate("TimetableWindow", "Вывести"))
        self.BackButton.setText(_translate("TimetableWindow", "Назад"))
        self.label_6.setText(_translate("TimetableWindow", "Станция прибытия:"))
        self.reverseBut.setText(_translate("TimetableWindow", "<=>"))
