# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrueFalseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 720)
        self.Train1 = QtWidgets.QLineEdit(Form)
        self.Train1.setGeometry(QtCore.QRect(30, 120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Train1.setFont(font)
        self.Train1.setObjectName("Train1")
        self.Train2 = QtWidgets.QLineEdit(Form)
        self.Train2.setGeometry(QtCore.QRect(260, 120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Train2.setFont(font)
        self.Train2.setObjectName("Train2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ComleteBut = QtWidgets.QPushButton(Form)
        self.ComleteBut.setGeometry(QtCore.QRect(30, 400, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComleteBut.setFont(font)
        self.ComleteBut.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ComleteBut.setObjectName("ComleteBut")
        self.ResultText = QtWidgets.QTextBrowser(Form)
        self.ResultText.setGeometry(QtCore.QRect(30, 310, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ResultText.setFont(font)
        self.ResultText.setObjectName("ResultText")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.BackButton = QtWidgets.QPushButton(Form)
        self.BackButton.setGeometry(QtCore.QRect(270, 620, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BackButton.setObjectName("BackButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Проверка на встречу"))
        self.label.setText(_translate("Form", "Поезд №1"))
        self.label_2.setText(_translate("Form", "Поезд №2"))
        self.ComleteBut.setText(_translate("Form", "Рассчитать"))
        self.ResultText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Form", "Ответ:"))
        self.BackButton.setText(_translate("Form", "Назад"))
